name: tagmeea
description: Tagmeea Waste
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+14

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_svg: ^2.0.0+1
  http: ^0.13.6
  dio: ^5.0.3
  loader_overlay: ^4.0.0
  quiver: ^3.2.1
  email_validator: ^2.1.16
  shared_preferences: ^2.0.17
  flutter_feather_icons: ^2.0.0
  convex_bottom_bar: ^3.2.0
  simple_circular_progress_bar: ^1.0.2
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.1.0
  intl_phone_number_input: ^0.7.2
  regexpattern: ^2.1.0
  fzregex: ^2.0.0
  functional_widget: ^0.10.1
  flutter_no_internet_widget: ^1.0.0+18-dev.1
  cached_network_image: ^3.2.3
  flutter_slidable: ^3.0.1
  flutter_screenutil: ^5.7.0
  dotted_border: ^2.0.0+3
  getwidget: ^4.0.0
  intl: ^0.18.1
  connectivity_plus: ^3.0.6
  connectivity_widget: ^1.0.0
  event: ^2.1.2
  qr_flutter: ^4.0.0
  internet_connection_checker:
  enhanced_future_builder: ^2.0.0
  settings_ui: ^2.0.2
  dialog_loader: ^0.0.3+3
  after_layout: ^1.2.0
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^16.3.2
  flutter_background_service: ^5.0.5
  flutter_background_service_ios: ^5.0.0
  flutter_background_service_android: ^6.2.2
  permission_handler: ^11.2.0
  flutter_barcode_scanner: ^2.0.0
  mobile_scanner: ^3.4.1
  awesome_notifications_core: ^0.9.1 # <~ always ensure to use the latest version
  awesome_notifications: any # <~ this version is managed by awesome_notifications_core package
  device_info_plus: ^9.1.1
  animated_bottom_navigation_bar: ^1.3.3
  bottom_bar: ^2.0.3
  image_picker: ^1.0.7
  awesome_dialog: ^3.2.0
  json_theme: ^6.4.0
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_to_model: ^3.0.1
  flutter_lints: ^3.0.1
  cart_stepper: ^4.1.1
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/img/
    - assets/img/status/
    - assets/themes/
  fonts:
    - family: Tajawal
      fonts:
        - asset: 'assets/fonts/Tajawal_Regular.ttf'
        - asset: 'assets/fonts/Tajawal_Bold.ttf'
          weight: 500
        - asset: 'assets/fonts/Tajawal-Medium.ttf'
          weight: 300
    - family: Anton
      fonts:
        - asset: 'assets/fonts/Anton-Regular.ttf'


flutter_native_splash:
  color: "#B7C9D9"
  background_image: "assets/img/company.png"
  image: assets/img/cartoon_businessman.png
  android_12:
    image: assets/img/cartoon_businessman.png
    color: "#B7C9D9"
    branding: assets/img/dart.png
    icon_background_color: "#111111"
    fullscreen: true

